### PR TITLE
Moral degenerates

### LINKED ISSUE #18: Make EPSILON a class property, not global
The module-level global is problematic. As outlined here: https://github.com/mapbox/rasterio/issues/430#issuecomment-205857304

```
>>> import affine as affineA
>>> import affine as affineB
>>> affineA.EPSILON
1e-05
>>> affineB.EPSILON
1e-05
>>> instA = affineA.Affine(0.001215, 0.0, -120.9375, 0.0, -0.001215, 38.823)
>>> instA.is_degenerate
True
>>> affineA.set_epsilon(1e-20)
>>> instA.is_degenerate  # doesn't change existing instances
True
>>> instB = affineB.Affine(0.001215, 0.0, -120.9375, 0.0, -0.001215, 38.823)
>>> instB.is_degenerate  # but it does change new instances, even from different module names
False
>>> affineB.EPSILON
1e-20
>>> affineA.EPSILON
1e-20
```

Three thoughts
* We should address this by making epsilon a property of the Affine class, not a global.
* add a `Affine.adjust_epsilon_assume_invertable()` method as a convenience method to check for invertability and bump up the epsilon for that instance under the assumption that it is invertable. Similarly we could have a flag to turn off is_degenerate checks for an instance.
* Would there be any harm in defaulting the EPSILON to a very low value like `1e-40`?

### PR DESCRIPTION
**Pull request by sgillies**
Closes #18

### CODE REVIEW

**Comment by sgillies** [comment]
@perrygeo I'm offering this one as an alternative to #19. This PR doesn't touch much of the implementation except to turn predicate properties that were using the global epsilon into methods that take a precision keyword argument (defaulting to 1.0e-5).

It also removes any precision from the degeneracy test, now it's just `self.determinant == 0.0` and that seems to work fine.

**Comment by perrygeo** [comment]
This looks great. Def. a breaking change since many properties become methods. But I think it's a good move.

I wonder if we could apply the degeneracy test of `self.determinant == 0.0` to the 1.2.x branch since that solves the original issue of certain raster affines being uninvertible with decimal degree units.

Also a left field, totally wacky idea to maintain backwards compatibility. I wonder if there is a way to create a hybrid property-method such that `self.prop` would dispatch to `self.prop()` and `self.prop(**kwargs)` would just work.

**Comment by sgillies** [comment]
Bonus 100% coverage :)

**Comment by perrygeo** [comment]
FWIW, I did find a way to make properties callable so that we could keep using them as properties or optionally as methods. Via @kezabelle : https://gist.github.com/kezabelle/43f45edefdcd1377b70eb171d4cffd1e#file-property_method-py

Not sure if this is something you'd be interested in implementing for the sake of backwards compat? But it proves that it *can* be done. Leaving it here just in case.

**Comment by sgillies** [comment]
@perrygeo I like it!

**Comment by sgillies** [comment]
In the end, I think it's best for precision to be a Affine instance attribute and not add a complex descriptor.

**Comment by sgillies** [comment]
Please ignore the noise caused by my fumbling fingers.

**Pull request merged**
